stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
sast:
  stage: review
  script:
    - echo "Reviewing with SAST"
include:
- template: Auto-DevOps.gitlab-ci.yml

lint:
  image: node:lts
  before_script:
    - npm install --progress=false
  stage: test
  script: npm run lint

build:
  stage: build
  script: docker build .

build_dist:
  needs:
    - build
  image: node:lts
  stage: build
  before_script:
    - npm install --progress=false
  script: npm run build
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - dist

build_img:
  needs:
    - build
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - tags

build_img_latest:
  needs:
    - build
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
